host_tz: "America/Chicago"

# Credentials used for both registry and mirror
docker_registry_username: "{{dockerRegistry.username}}"
docker_registry_password: "{{dockerRegistry.password}}"

docker_registry_host: https://registry.nas.local.abbottland.io
docker_registry_port: 5000
docker_registry_ui_port: 5001

docker_registry_mirror_host: https://registry-mirror.nas.local.abbottland.io
docker_registry_mirror_port: 5002
docker_registry_mirror_ui_port: 5003

drone_server_host: drone.abbottland.io
drone_server_user_filter: pbabbott
drone_server_admin: pbabbott

verdaccio_public_proto: https
verdaccio_public_url: verdaccio.nas.local.abbottland.io
verdaccio_user: pbabbott
verdaccio_pw: "{{ verdaccio.pbabbott_password }}"
