- name: Traefik configuration for drone
  hosts: bananapi
  roles:
    - role: abbottland.ingress.traefik_app
      traefik_app_file_name: 'drone.yml'

- name: Drone Docker Installations on RPI (not root)
  hosts: rpi
  roles:
    - role: home.drone-server
    - role: home.drone-docker-runner

# TODO: Setup elder_wand drone configuration with ansible.