
# https://docs.ansible.com/ansible/latest/collections/community/docker/docker_prune_module.html

- name: Docker Cleanup
  hosts:
    - dumbledore
    - room_of_requirement
    - bananapi
  tasks:
    - name: Prune everything
      community.docker.docker_prune:
        containers: true
        images: true
        networks: true
        volumes: true
        builder_cache: true
