
# Example commands
# ansible-playbook -e @./vault.yml -i inventories/nonprod ./playbooks/kubernetes-gen2/ping.yml
# ansible-playbook -e @./vault.yml -i inventories/prod ./playbooks/kubernetes-gen2/ping.yml

- name: Ping kubernetes hosts
  hosts:
    - kubernetes_controllers
    - kubernetes_workers
  tasks:
    - name: Ping host
      ansible.builtin.ping: {}
