- name: Restart homeassistant container
  community.docker.docker_container:
    name: homeassistant
    restart: true

# - name: Restart mosquitto container
#   community.docker.docker_container:
#     name: mosquitto
#     restart: true

# - name: Restart zigbee2mqtt container
#   community.docker.docker_container:
#     name: zigbee2mqtt
#     restart: true

