# https://docs.sunfounder.com/projects/pironman/en/latest/setup_pironman.html

- name: Update Apt and install tools
  hosts:
    - dumbledore
  become: true
  roles:
    - role: abbottland.core.apt
      apt_install_packages:
        - git
        - python3
        - python3-pip
        - python3-setuptools

- name: Clone pironman codebase & run installer
  hosts:
    - dumbledore
  tasks:
    - name: Example clone of a single branch
      ansible.builtin.git:
        repo: https://github.com/sunfounder/pironman.git
        dest: "{{ pironman_tools_directory }}"
        single_branch: yes
        version: v2.0
        force: false

    - name: Run pironman installer
      become: true
      ansible.builtin.command: python3 install.py --skip-reboot
      args:
        chdir: "{{ pironman_tools_directory }}"

- name: Clone pironman codebase & run installer
  hosts:
    - dumbledore
  become: true
  tasks:
    - name: Ensure /boot/config.txt file has proper contents
      block:
      - name: GPIO pin 26
        ansible.builtin.lineinfile:
          regexp: 'dtoverlay=gpio-poweroff,gpio_pin=26,active_low=0'
          line: 'dtoverlay=gpio-poweroff,gpio_pin=26,active_low=0'
          path: /boot/config.txt
      - name: GPIO pin 13
        ansible.builtin.lineinfile:
          regexp: 'dtoverlay=gpio-ir,gpio_pin=13'
          line: 'dtoverlay=gpio-ir,gpio_pin=13'
          path: /boot/config.txt

#rgb_color = 0a1aff
- name: Set config file
  hosts:
    - dumbledore
  tasks:
    - name: Copy config file to remote
      ansible.builtin.copy:
        src: ./files/config.txt
        dest: "/opt/pironman/config.txt"
      notify:
        - Restart Pironman
  handlers:
    - name: Restart Pironman
      become: true
      ansible.builtin.command: pironman restart
      args:
        chdir: "{{ pironman_tools_directory }}"