# TODO: update mealie_data path to be a variable

- ansible.builtin.file:
    path: /home/pi/grafana
    state: directory
    mode: '0755'

- ansible.builtin.file:
    path: /home/pi/grafana/data
    state: directory
    mode: '0755'  

- community.docker.docker_compose:
    project_name: grafana
    
    definition:
      version: "3.1"
      networks:
        default:
          name: lsio
          external: true
      services:
        grafana:
          image: grafana/grafana-enterprise:latest
          container_name: grafana
          restart: always
          environment:
            GF_AUTH_ANONYMOUS_ENABLED: 'true'
            GF_AUTH_ANONYMOUS_ORG_NAME: 'Main Org.'
            GF_AUTH_ANONYMOUS_ORG_ROLE: 'Admin'
            GF_AUTH_BASIC_ENABLED: 'false'
            GF_AUTH_DISABLE_LOGIN_FORM: 'true'
          ports:
            - "3002:3000"
          user: "1001"
          volumes:
            - /home/pi/grafana/data:/var/lib/grafana
