- ansible.builtin.file:
    path: "{{ verdaccio_config_dir }}"
    state: directory
    mode: '0755'  
    owner: 10001
    group: 65533

- ansible.builtin.file:
    path: "{{ verdaccio_storage_dir }}"
    state: directory
    mode: '0755'
    owner: 10001
    group: 65533

- ansible.builtin.file:
    path: "{{ verdaccio_plugins_dir }}"
    state: directory
    mode: '0755'  
    owner: 10001
    group: 65533

- name: Copy config.yaml to remote
  register: conf
  ansible.builtin.copy:
    src: ./files/config.yaml
    dest: "{{ verdaccio_config_dir }}/config.yaml"

# TODO: figure out how to add a user after the service is up with npm adduser
# - name: Add a user to a password file and ensure permissions are set
#   community.general.htpasswd:
#     path: "{{ verdaccio_config_dir }}/htpasswd"
#     name: "{{ verdaccio_user }}"
#     password: "{{ verdaccio_pw }}"
#     owner: 10001
#     group: 65533
#     mode: 0644

- name: restart verdaccio container
  docker_container:
    name: verdaccio
    restart: true
  when: conf.changed 

- community.docker.docker_compose:
    project_name: verdaccio
    
    definition:
      version: '3.1'
      services:
        verdaccio:
          user: "10001:65533"
          container_name: verdaccio
          image: verdaccio/verdaccio
          network_mode: host
          environment:
            - VERDACCIO_PORT=4873
          volumes:
            - '{{ verdaccio_storage_dir }}:/verdaccio/storage'
            - '{{ verdaccio_config_dir }}:/verdaccio/conf'
            - '{{ verdaccio_plugins_dir }}:/verdaccio/plugins'
          restart: always