- ansible.builtin.file:
    path: "{{ verdaccio_config_dir }}"
    state: directory
    mode: '0755'  
    owner: "{{verdaccio_owner}}"
    group: "{{verdaccio_group}}"

- ansible.builtin.file:
    path: "{{ verdaccio_storage_dir }}"
    state: directory
    mode: '0755'
    owner: "{{verdaccio_owner}}"
    group: "{{verdaccio_group}}"

- ansible.builtin.file:
    path: "{{ verdaccio_plugins_dir }}"
    state: directory
    mode: '0755'  
    owner: "{{verdaccio_owner}}"
    group: "{{verdaccio_group}}"

- name: Copy config.yaml to remote
  register: conf
  ansible.builtin.copy:
    src: ./files/config.yaml
    dest: "{{ verdaccio_config_dir }}/config.yaml"

- name: Setup npm users
  register: password
  community.general.htpasswd:
    path: "{{ verdaccio_config_dir }}/htpasswd"
    name: "{{ verdaccio_user }}"
    password: "{{ verdaccio_pw }}"
    owner: "{{verdaccio_owner}}"
    group: "{{verdaccio_group}}"
    mode: 0640
    crypt_scheme: md5_crypt

- community.docker.docker_compose:
    project_name: verdaccio
    
    definition:
      version: '3.1'
      services:
        verdaccio:
          user: "{{verdaccio_owner}}:{{verdaccio_group}}"
          container_name: verdaccio
          image: verdaccio/verdaccio
          network_mode: host
          environment:
            - VERDACCIO_PORT=4873
            - VERDACCIO_PUBLIC_URL='{{verdaccio_public_proto}}://{{verdaccio_public_url}}'
          volumes:
            - '{{ verdaccio_storage_dir }}:/verdaccio/storage'
            - '{{ verdaccio_config_dir }}:/verdaccio/conf'
            - '{{ verdaccio_plugins_dir }}:/verdaccio/plugins'
          restart: always

- name: restart verdaccio container
  docker_container:
    name: verdaccio
    restart: true
  when: conf.changed or password.changed
