
- name: Setup Wireguard
  hosts: bananapi
  handlers:
    - name: Restart wireguard container
      community.docker.docker_container:
        name: wireguard
        restart: true
  tasks:
    - name: Ensure wireguard config directory exists
      ansible.builtin.file:
        path: "{{ wireguard_config_dir }}"
        state: directory
        mode: '0755'  
    # - name: Copy configuration file to remote
    #   ansible.builtin.copy:
    #     src: ./files/conf.yml
    #     dest: "{{ dashy_config_dir }}/conf.yml"
    #   notify:
    #     - Restart dashy container
    - name: Ensure wireguard is up-and-running
      community.docker.docker_compose:
        project_name: wireguard
        definition:
          version: "3.7"
          services:
            wireguard:
              image: ghcr.io/linuxserver/wireguard
              container_name: wireguard
              cap_add:
                - NET_ADMIN
                - SYS_MODULE
              restart: always
              environment:
                PUID: "{{ host_puid }}"
                PGID: "{{ host_pgid }}"
                TZ: "{{ host_tz }}"
                SERVERURL: vpn.abbottland.io
                SERVERPORT: 51820
                PEERS: 2
              volumes:
                - "{{ wireguard_config_dir }}:/config"
                - /lib/modules:/lib/modules
              ports:
                - 51820:51820/udp
              sysctls:
                - net.ipv4.conf.all.src_valid_mark=1