
- name: Ensure docker registry directories exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop: "{{ registry_configuration_directories }}"

- name: Template a file to /config/temp.yml
  ansible.builtin.template:
    src: ./templates/config.j2
    dest: "{{ docker_registry_config_dir }}/temp.yml"

- name: Setup registry user
  register: password
  when: not docker_registry_proxy_enabled
  community.general.htpasswd:
    path: "{{ docker_registry_config_dir }}/htpasswd"
    name: "{{ docker_registry_username }}"
    password: "{{ docker_registry_password }}"
    crypt_scheme: bcrypt
      
- name: Replace existing config
  ansible.builtin.copy:
    remote_src: true
    src: "{{ docker_registry_config_dir }}/temp.yml"
    dest: "{{ docker_registry_config_dir }}/config.yml"
  notify:
    - Restart registry container

- name: Remove temporary file
  ansible.builtin.file:
    path: "{{ docker_registry_config_dir }}/temp.yml"
    state: absent

- name: Ensure registry_mirror and registry_mirror_ui are running
  community.docker.docker_compose:
    project_name: "{{ docker_registry_project_name }}"
    
    definition:
      version: '3.1'
      services:
        registry_mirror:
          restart: always
          image: registry:2
          container_name:  "registry{{ container_suffix }}"  
          ports:
            - "{{ docker_registry_port }}:5000"
          volumes: "{{ docker_registry_default_volume_mounts + ([] if docker_registry_proxy_enabled else docker_registry_auth_mount) }}"

        registry_mirror_ui:
          restart: always
          image: joxit/docker-registry-ui:latest
          container_name:  "registry_ui{{ container_suffix }}"  
          ports:
            - "{{ docker_registry_ui_port }}:80"
          environment:
            REGISTRY_TITLE: "{{ docker_registry_title }}"
            REGISTRY_URL: "{{ docker_registry_host }}"
            SINGLE_REGISTRY: "true"
            DELETE_IMAGES: "{{ (not docker_registry_proxy_enabled) | string }}"

