

- ansible.builtin.file:
    path: /home/pi/prometheus
    state: directory
    mode: '0755'

- name: Copy prometheus.yml to remote
  ansible.builtin.copy:
    src: ./files/prometheus.yml
    dest: "/home/pi/prometheus/prometheus.yml"
  register: prometheus_config

- community.docker.docker_compose:
    project_name: prometheus

    definition:
      version: "2.1"
      networks:
        default:
          name: lsio
          external: true

      services:
        prometheus:
          container_name: prometheus
          image: prom/prometheus
          restart: always
          ports:
            - 9090:9090
          volumes:
            - /home/pi/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml


- name: Restart prometheus container
  docker_container:
    name: prometheus
    restart: true
  when: prometheus_config.changed
