#TODO: Convert to playbook (1)
- name: Traefik configuration for registry and registry mirror
  hosts: bananapi
  roles:
    - role: home.traefik_app
      traefik_app_file_name: 'registry.nas.local.yml'

#TODO: Convert to playbook (1)
#TODO: Convert collection to role

- name: Setup Docker Registry on NAS
  hosts: room_of_requirement
  roles:
    # First registry is for publishing images.
    - role: abbottland.docker.docker_registry

    # Second registry is used as a pull-through cache (unable to push images to a mirror)
    - role: abbottland.docker.docker_registry
      docker_registry_host: "{{ docker_registry_mirror_host }}"
      docker_registry_title: "{{ docker_registry_mirror_title }}"
      docker_registry_config_dir: "{{ docker_registry_mirror_config_dir }}"
      docker_registry_storage_dir: "{{ docker_registry_mirror_storage_dir }}"
      docker_registry_port: "{{ docker_registry_mirror_port }}"
      docker_registry_ui_port: "{{ docker_registry_mirror_ui_port }}"
      docker_registry_proxy_enabled: true
      docker_hub_username: "{{ dockerHub.username }}"
      docker_hub_password: "{{ dockerHub.password }}"
