kind: pipeline
name: devcontainer
type: docker

platform:
  os: linux
  arch: arm64

trigger:
  ref:
    - refs/tags/*-dev

steps:
  - name: Publish dev image
    image: plugins/docker
    settings:
      registry: https://registry.nas.local.abbottland.io
      username: pbabbott
      password:
        from_secret: REGISTRY_PASSWORD
      mirror: https://registry-mirror.nas.local.abbottland.io
      repo: registry.nas.local.abbottland.io/home-playbooks-dev
      auto_tag: true
      dockerfile: ./.devcontainer/Dockerfile.dev
      context: ./.devcontainer/

---

kind: pipeline
name: semaphore
type: docker

platform:
  os: linux
  arch: arm64

trigger:
  ref:
    - refs/tags/*-semaphore

steps:
  - name: Publish dev image
    image: plugins/docker
    settings:
      registry: https://registry.nas.local.abbottland.io
      username: pbabbott
      password:
        from_secret: REGISTRY_PASSWORD
      mirror: https://registry-mirror.nas.local.abbottland.io
      repo: registry.nas.local.abbottland.io/semaphore
      tags:
        - latest
        - "${DRONE_TAG##v}"
      dockerfile: ./Dockerfile
      context: ./
