

- name: Set up SSH keys everywhere
  hosts: localhost
  roles:
    - home.ssh_readiness
    - home.ssh_keys
  vars:
    temp: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa.pub"
  tasks:
    - debug: msg={{temp}}
