# - hosts: rpi
#   name: Hello World
#   tasks:
#     - debug:
#         msg: "hello user: {{ansible_user}}"
#     - debug:
#         msg: deb [arch=arm64] https://download.docker.com/{{ ansible_system | lower }}/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable
#     - debug:
#         msg: "{{ playbook_dir }}"
    
- name: Install Prerequsites
  hosts: rpi
  become: true
  tasks:
    - name: Install Python3 pip
      apt:
        name: 
          - python3-pip
        update_cache: yes

- name: Install docker, and pip packages
  hosts: rpi
  become: true
  roles:
    - role: home.docker
  tasks:
    - ansible.builtin.pip:
        name: docker
    - ansible.builtin.pip:
        name: docker-compose

- hosts: rpi
  name: Install Mealie
  roles:
    - role: home.mealie


# # - name: Install Tools
# #   hosts: all
# #   roles:
# #     - role: home.neofetch
# #     - name: Configure Oh-My-ZSH
# #       role: gantsign.antigen_bundles
# #       users:
# #         - username: 
# #           antigen_libraries:
# #             - name: oh-my-zsh
# #           antigen_theme:
# #             name: gallois
# #           antigen_bundles:
# #             - name: git
# #             - name: command-not-found
# #             - name: you-should-use
# #             - name: autojump
# #             - name: zsh-autosuggestions

# # - name: Configure Local Computer
# #   hosts: localhost
# #   roles:
# #     - role: home.detect_shell
# #     - role: home.shell_config
# #       config_file_name: "{{ shell_interactive }}"
# #       aliases:
# #         - alias: ll
# #           command: ls -lh
# #         - alias: k
# #           command: kubectl
# #         - alias: python
# #           command: python3
# #       exports: 
# #         - key: PATH
# #           value: "$PATH:$HOME/.local/bin"
# #       ssh_targets:
# #         - shortcut: rpi
# #           username: "{{ hostvars.rpi.ansible_user }}"
# #           hostname: "{{ hostvars.rpi.ansible_host }}"
# #     - role: home.ssh_readiness
# #     - role: home.ssh_keys
