
- name: Setup prometheus server
  hosts:
    - room_of_requirement
  handlers:
    - name: Restart prometheus container
      community.docker.docker_container:
        name: prometheus
        restart: true
  tasks:
    - name: Ensure prometheus config directory exists
      ansible.builtin.file:
        path: "{{ prometheus_config_dir }}"
        state: directory
        mode: '0755'

    - name: Copy prometheus.yml to remote
      ansible.builtin.copy:
        src: ./files/prometheus.yml
        dest: "{{ prometheus_config_dir }}/prometheus.yml"
      register: prometheus_config
      notify:
        - Restart prometheus container

    - name: Ensure prometheus server docker container is running
      community.docker.docker_compose:
        project_name: prometheus
        definition:
          version: "3.1"
          networks:
            loki:
              name: grafana_loki
              driver: bridge
          services:
            prometheus:
              container_name: prometheus
              image: prom/prometheus
              restart: always
              ports:
                - 9090:9090
              volumes:
                - "{{ prometheus_config_dir }}/prometheus.yml:/etc/prometheus/prometheus.yml"
              networks:
                - loki

- name: Traefik configuration for prometheus
  hosts: bananapi
  roles:
  - role: home.traefik_app
    traefik_app_file_name: 'prometheus.nas.local.yml'
