# - name: Setup host metrics for PI
#   hosts:
#     - rpi
#     - bananapi
#   roles:
#     - role: cloudalchemy.node_exporter

# - name: Setup host metrics for NAS 
#   hosts: room_of_requirement
#   roles:
#     - role: home.prometheus-docker-node-exporter

# - name: Configure elder_wand
#   hosts: elder_wand
#   tasks:
#     - name: Firewall rule to allow HTTP on TCP port 9182
#       community.windows.win_firewall_rule:
#         name: Prometheus Metrics
#         localport: 9182
#         action: allow
#         direction: in
#         protocol: tcp
#         profiles: private
#         state: present
#         enabled: yes


# # TODO: setup prometheus metrics  
# # - role: abbottland.docker.docker_daemon
# #       docker_daemon_metrics_ip_address: "{{ ansible_host }}"


#     # - role: home.prometheus-server


