# NOTE: prometheus.prometheus.node_exporter requries systemd to function
# thus docker is used on NAS
- name: Setup host metrics for NAS
  hosts: room_of_requirement
  tasks:
    - name: Ensure node_exporter is running
      community.docker.docker_compose:
        project_name: node_exporter
        definition:
          version: '3.8'
          services:
            node_exporter:
              image: quay.io/prometheus/node-exporter:latest
              container_name: node_exporter
              ports:
                - 9100:9100
              command:
                - '--path.rootfs=/host'
              pid: host
              restart: always
              volumes:
                - '/:/host:ro'

- name: Metrics - node_exporter
  hosts:
    - web_servers
    - chimaera
  roles:
    - role: prometheus.prometheus.node_exporter
