

- name: Setup NPM Registry on NAS
  hosts: room_of_requirement
  roles:
    - role: home.verdaccio

- name: Traefik configuration for verdaccio
  hosts: bananapi
  roles:
    - role: home.traefik_app
      traefik_app_file_name: 'verdaccio.nas.local.yml'

- name: Get token from verdaccio
  import_playbook: ./get_token.yml

# - name: Configure elder_wand to connect to registry
#   hosts: elder_wand
#   tasks:
#     - name: Ping host
#       ansible.windows.win_ping: {}

#     - name: Copy a single file
#       ansible.windows.win_copy:
#         src: ./files/.npmrc
#         dest: C:\Users\pbabb\.npmrc

#     - name: Set an environment variable for machine (NPM_REGISTRY)
#       ansible.windows.win_environment:
#         state: present
#         name: NPM_REGISTRY
#         value: "{{ verdaccio_public_url }}"
#         level: machine

#     - name: Set an environment variable for machine (NPM_REGISTRY_PROTO)
#       ansible.windows.win_environment:
#         state: present
#         name: NPM_REGISTRY_PROTO
#         value: "{{ verdaccio_public_proto }}"
#         level: machine

#     - name: Set an environment variable for machine (NPM_TOKEN)
#       ansible.windows.win_environment:
#         state: present
#         name: NPM_TOKEN
#         value: "{{ hostvars['room_of_requirement'].verdaccio_token }}"
#         level: machine
