- name: Use docker to setup grafana & loki
  hosts:
    - room_of_requirement
  roles:
    - role: home.grafana-loki

#TODO: Vector eats up too much log disk space
- name: Use docker to setup vector
  hosts:
    - room_of_requirement
    - web_servers
  roles:
    - role: home.vector

- name: Traefik configuration for drone
  hosts: bananapi
  roles:
    - role: home.traefik_app
      traefik_app_file_name: 'grafana.nas.local.yml'
    - role: home.traefik_app
      traefik_app_file_name: 'loki.nas.local.yml'
