http:
  middlewares:
    addprefix-pihole:
      addPrefix:
        prefix: "/admin"
    # TODO: figure out how to fix this.
    # redirect-pihole-admin:
    #   redirectRegex:
    #     regex: "^https:\\/\\/pihole\\.local\\.abbottland\\.io\\/admin$"
    #     replacement: "https://pihole.local.abbottland.io"
      
  routers:
     to-pihole-https:
      entryPoints:
        - "https"
      rule: "Host(`pihole.local.abbottland.io`)"
      middlewares:
        - secured
        - addprefix-pihole
        # - redirect-pihole-admin
      tls: {}
      service: pihole

  services:
    pihole:
      loadBalancer:
        servers:
        - url: http://192.168.4.144:8081
        passHostHeader: true