http:
  routers:
    to-roomofrequirement-https:
      entryPoints:
        - "https"
      rule: "Host(`roomofrequirement.local.abbottland.io`)"
      middlewares:
        - secured
      service: roomofrequirement
      tls: {}

  services:
    roomofrequirement:
      loadBalancer:
        servers:
        - url: http://192.168.4.124:9000
        passHostHeader: true