http:

  # middlewares:
  #   verdaccio-headers:
  #     headers:
  #       customRequestHeaders:
  #         Host: verdaccio.nas.local.abbottland.io
  #         X-Forwarded-Proto: https

  routers:
    to-verdaccio-nas-https:
      entryPoints:
        - "https"
      rule: "Host(`verdaccio.nas.local.abbottland.io`)"
      middlewares:
        - secured
        # - verdaccio-headers
      service: verdaccio-nas
      tls: {} 

  services:
    verdaccio-nas:
      loadBalancer:
        servers:
        - url: http://192.168.4.124:4873
        passHostHeader: true