http:
  routers:
    to-homeassistant-https:
      entryPoints:
        - "https"
      rule: "Host(`homeassistant.abbottland.io`)"
      service: homeassistant
      tls: {}

  services:
    homeassistant:
      loadBalancer:
        servers:
          - url: http://192.168.4.24:8123
        passHostHeader: true
