http:
  routers:
    to-homeassistant-https:
      entryPoints:
        - "https"
      rule: "Host(`homeassistant.local.abbottland.io`)"
      middlewares:
        - secured
      tls: {}
      service: homeassistant

  services:
    homeassistant:
      loadBalancer:
        servers:
          - url: http://192.168.4.157:8123
        passHostHeader: true
  
    