http:
  routers:
    to-mealie-https:
      entryPoints:
        - "https"
      rule: "Host(`mealie.abbottland.io`)"
      service: mealie
      tls: {}

  services:
    mealie:
      loadBalancer:
        servers:
        - url: http://192.168.4.24:9925
        passHostHeader: true