

    # - name: Download tigera-operator.yaml
    #   ansible.builtin.get_url:
    #     url: https://raw.githubusercontent.com/projectcalico/calico/v3.27.3/manifests/tigera-operator.yaml
    #     dest: "/tmp/tigera-operator.yaml"
    #     force: yes
    # - name: Apply tigera-operator.yaml
    #   kubernetes.core.k8s:
    #     state: present
    #     src: "/tmp/tigera-operator.yaml"

    # - name: Copy custom-resources.yaml
    #   ansible.builtin.copy:
    #     src: ./files/custom-resources.yaml
    #     dest: /tmp/custom-resources.yaml
    # - name: Apply custom-resources.yaml
    #   kubernetes.core.k8s:
    #     state: present
    #     src: "/tmp/custom-resources.yaml"

  # - name: Download kube-flannel.yml
  #   ansible.builtin.get_url:
  #     url: https://github.com/flannel-io/flannel/releases/latest/download/kube-flannel.yml
  #     dest: "/tmp/kube-flannel.yml"
  #     force: yes
  # - name: Apply kube-flannel.yml
  #   kubernetes.core.k8s:
  #     state: present
  #     src: "/tmp/kube-flannel.yml"

# TODO: bring down the bridge if flannel changed
# sudo ip link delete cni0 type bridge
# TODO: may need to restart coredns ?
