
- name: Ping linux hosts
  hosts:
    - web_servers
    - room_of_requirement
  tasks:
    - name: Ping host
      ansible.builtin.ping: {}


- name: Configure elder_wand
  hosts: elder_wand
  tasks:
    - name: Ping host
      ansible.windows.win_ping: {}
