
- name: Fetch fnm
  ansible.builtin.uri:
    url: https://fnm.vercel.app/install
    return_content: yes
  register: fnm_installer

- name: Run fnm installer
  ansible.builtin.shell:
    cmd: bash
    stdin: "{{ fnm_installer.content }}"