- name: Setup pihole backups
  hosts:
    - bananapi
  tasks:
    - name: Ensure pihole app config directory exists
      ansible.builtin.file:
        path: "{{ cron_scripts_dir }}"
        state: directory
        mode: '0755'

    - name: Remove old files nightly
      block:
        - name: Copy the remove_old_backups.sh script
          copy:
            src: ./files/remove_old_backups.sh
            dest: "{{ cron_scripts_dir }}"
            mode: 0755

        - name: Create cron job for pihole backup
          cron:
            name: "Pihole cleanup"
            special_time: "daily"
            job: "{{ cron_scripts_dir }}/remove_old_backups.sh >{{cron_scripts_dir}}/remove_old_backups.log 2>&1"
            user: "{{ ansible_user }}"

    - name: Run backups nightly
      block:
        - name: Copy the pihole-backup.sh script
          copy:
            src: ./files/pihole_backup.sh
            dest: "{{ cron_scripts_dir }}"
            mode: 0755

        - name: Create cron job for pihole backup
          cron:
            name: "Pihole backup"
            special_time: "daily"
            job: "{{ cron_scripts_dir }}/pihole_backup.sh >{{cron_scripts_dir}}/pihole_backup.log 2>&1"
            user: "{{ ansible_user }}"
