- hosts:
    - bananapi
    - dumbledore
  name: Test web_server group vars
  tasks:
    - name: Test one_cool_var
      debug:
        msg: "dns_nameservers: {{ dns_nameservers }}"
    - name: Output inventory name
      debug:
        msg: "{{ inventory_hostname }}"
