- ansible.builtin.file:
    path: /home/pi/swag/nginx/site-confs
    state: directory
    mode: '0755' 

- name: Copy nginx.conf to remote
  register: nginx_conf
  ansible.builtin.copy:
    src: ./files/nginx.conf
    dest: "/home/pi/swag/nginx/site-confs/default"

- ansible.builtin.file:
    path: /home/pi/swag/nginx/proxy-confs
    state: directory
    mode: '0755'  

- name: Enable mealie configuration
  register: mealie_proxy_conf
  ansible.builtin.copy:
    src: ./files/mealie.subdomain.conf
    dest: /home/pi/swag/nginx/proxy-confs/mealie.subdomain.conf

- name: Enable drone configuration
  register: drone_proxy_conf
  ansible.builtin.copy:
    src: ./files/drone.subdomain.conf
    dest: /home/pi/swag/nginx/proxy-confs/drone.subdomain.conf

- name: restart swag container
  docker_container:
    name: swag
    restart: true
  when: nginx_conf.changed or mealie_proxy_conf.changed or drone_proxy_conf.changed

# https://hub.docker.com/r/linuxserver/swag
- community.docker.docker_compose:
    project_name: swag
    definition:
      version: "2.1"
      networks:
        default:
          name: lsio
          external: true
      services:
        swag:
          image: linuxserver/swag
          container_name: swag
          cap_add:
            - NET_ADMIN
          environment:
            PUID: 1001
            PGID: 1001
            TZ: America/Los_Angeles
            URL: abbottland.duckdns.org
            SUBDOMAINS: wildcard
            VALIDATION: duckdns
            DUCKDNSTOKEN: "{{ duckdns.token }}"
          volumes:
            - /home/pi/swag:/config
          ports:
            - 443:443
            - 80:80
          restart: unless-stopped





