- name: Install semaphore on target
  hosts: dumbledore
  tasks:
    - name: Ensure semaphore_postgres_data_dir exists
      ansible.builtin.file:
        path: "{{ semaphore_postgres_data_dir }}"
        state: directory
    - name: Get semaphore up-and-running with docker-compose
      community.docker.docker_compose:
        project_name: semaphore
        definition:
          version: "3.1"
          services:
            postgres:
              restart: unless-stopped
              image: "{{ semaphore_postgres_docker_image }}"
              hostname: postgres
              # ports:
              #   - 5432:5432
              volumes:
                - "{{ semaphore_postgres_data_dir }}:/var/lib/postgresql/data"
                - /etc/timezone:/etc/timezone:ro
                - /etc/localtime:/etc/localtime:ro
              environment:
                TZ: "{{ host_tz }}"
                PGTZ: "{{ host_tz }}"
                POSTGRES_USER: semaphore
                POSTGRES_PASSWORD: "{{ semaphore.postgres.password }}"
                POSTGRES_DB: semaphore
            semaphore:
              container_name: semaphore
              # image: semaphoreui/semaphore:latest
              image: "{{ semaphore_image }}"
              restart: always
              ports:
                - 3001:3000
              depends_on:
                - postgres
              volumes:
                - /etc/timezone:/etc/timezone:ro
                - /etc/localtime:/etc/localtime:ro
              environment:
                TZ: "{{ host_tz }}"
                SEMAPHORE_DB: semaphore
                SEMAPHORE_DB_DIALECT: postgres
                SEMAPHORE_DB_PORT: 5432
                SEMAPHORE_DB_USER: semaphore
                SEMAPHORE_DB_PASS: "{{ semaphore.postgres.password }}"
                SEMAPHORE_DB_HOST: postgres

                SEMAPHORE_ADMIN_PASSWORD: "{{ semaphore.admin.password }}"
                SEMAPHORE_ADMIN_NAME: "{{ semaphore.admin.name }}"
                SEMAPHORE_ADMIN_EMAIL: "{{ semaphore.admin.email }}"
                SEMAPHORE_ADMIN: "{{ semaphore.admin.name }}"
                SEMAPHORE_ACCESS_KEY_ENCRYPTION: "{{ semaphore.accessKey }}"
                SEMAPHORE_LDAP_ACTIVATED: 'no' # if you wish to use ldap, set to: 'yes'


- name: Traefik configuration for semaphore
  hosts: bananapi
  roles:
    - role: home.traefik_app
      traefik_app_file_name: 'semaphore.yml'

- ansible.builtin.import_playbook: './update_notifications.yml'
