- name: Install semaphore on target
  hosts: dumbledore
  tasks:
    - name: Ensure semaphore_postgres_data_dir exists
      ansible.builtin.file:
        path: "{{ semaphore_postgres_data_dir }}"
        state: directory
    - name: Get semaphore up-and-running with docker-compose
      community.docker.docker_compose:
        project_name: semaphore
        definition:
          version: "3.1"
          services:
            postgres:
              restart: unless-stopped
              image: "{{ semaphore_postgres_docker_image }}"
              hostname: postgres
              volumes:
                - "{{ semaphore_postgres_data_dir }}:/var/lib/postgresql/data"
              environment:
                TZ: "{{ host_tz }}"
                POSTGRES_USER: semaphore
                POSTGRES_PASSWORD: "{{ semaphore.postgres.password }}"
                POSTGRES_DB: semaphore
            semaphore:
              container_name: semaphore
              # image: semaphoreui/semaphore:latest
              image: registry.nas.local.abbottland.io/semaphore:0.0.8-semaphore
              restart: always
              ports:
                - 3001:3000
              depends_on:
                - postgres
              environment:
                TZ: "{{ host_tz }}"
                SEMAPHORE_DB: semaphore
                SEMAPHORE_DB_DIALECT: postgres
                SEMAPHORE_DB_PORT: 5432
                SEMAPHORE_DB_USER: semaphore
                SEMAPHORE_DB_PASS: "{{ semaphore.postgres.password }}"
                SEMAPHORE_DB_HOST: postgres

                SEMAPHORE_ADMIN_PASSWORD: "{{ semaphore.admin.password }}"
                SEMAPHORE_ADMIN_NAME: "{{ semaphore.admin.name }}"
                SEMAPHORE_ADMIN_EMAIL: "{{ semaphore.admin.email }}"
                SEMAPHORE_ADMIN: "{{ semaphore.admin.name }}"
                SEMAPHORE_ACCESS_KEY_ENCRYPTION: "{{ semaphore.accessKey }}"
                SEMAPHORE_LDAP_ACTIVATED: 'no' # if you wish to use ldap, set to: 'yes'


- name: Traefik configuration for semaphore
  hosts: bananapi
  roles:
    - role: home.traefik_app
      traefik_app_file_name: 'semaphore.yml'

- name: Diun configuration for semaphore and postgres
  hosts: dumbledore
  roles:
    - role: home.diun_file
      diun_file_name: 'semphore_postgres.yml'
      diun_watch_image: "{{ semaphore_postgres_docker_image }}"
  tasks:
    - name: Copy Dockerfile to remote
      ansible.builtin.copy:
        src: ./files/Dockerfile
        dest: "{{ diun_dynamic_config_dir }}/semaphore.Dockerfile"
