## Static Configuration
api:
  insecure: true
entryPoints:
  http:
    address: :80
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
          permanent: true
  https:
    address: :443
serversTransport:
    insecureSkipVerify: true
providers:
  file:
    directory: /etc/traefik/conf.d/
    watch: true
certificatesResolvers:
  cloudflareResolver:
    acme:
      email: pbabbott@gmail.com
      storage: /etc/traefik/acme.json
      dnsChallenge:
        provider: cloudflare
global:
  checkNewVersion: true
  sendAnonymousUsage: true
metrics:
  prometheus: {}
accessLog:
  filePath: /etc/traefik/access.log
log:
  level: WARN