## Static Configuration

global:
  checkNewVersion: true
  sendAnonymousUsage: true

serversTransport:
    insecureSkipVerify: true

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true

  websecure:
    address: :443

api:
  insecure: true

providers:
  file:
    directory: /etc/traefik/conf.d/

metrics:
  prometheus: {}

# accessLog:
  # filePath: /etc/traefik/access.log

certificatesResolvers:
  cloudflareResolver:
    acme:
      email: pbabbott@gmail.com
      storage: acme.json
      dnsChallenge:
        provider: cloudflare
  
log:
  level: WARN