## Static Configuration

global:
  checkNewVersion: true
  sendAnonymousUsage: true

serversTransport:
    insecureSkipVerify: true

entryPoints:
  web:
    address: :80

  websecure:
    address: :443

api:
  insecure: true

providers:
  file:
    directory: /etc/traefik/conf.d/

accessLog:
  filePath: /etc/traefik/access.log

certificatesResolvers:
  cloudflareResolver:
    acme:
      email: pbabbott@gmail.com
      storage: acme.json
      dnsChallenge:
        provider: cloudflare
  
log:
  level: WARN