
- name: ssh_copy_id to raspberry pi
  include_role:
    name: ryankwilliams.ssh_copy_id
  vars:
    hostname: "{{ hostvars.rpi.ansible_host }}"
    username: "{{ hostvars.rpi.ansible_user }}"
    password: "{{ hostvars.rpi.ansible_password }}"
    ssh_public_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa.pub"
    ssh_port: 22
