

- ansible.builtin.file:
    path: "{{ pihole_config_dir }}"
    state: directory
    mode: '0755'  

- community.docker.docker_compose:
    project_name: pihole
    
    definition: 
      version: "3"
      services:
        pihole:
          container_name: pihole
          image: pihole/pihole:latest
          ports:
            - "53:53/tcp"
            - "53:53/udp"
            - "8081:80/tcp"
          environment:
            TZ: "{{ host_tz }}"
            WEBPASSWORD: "{{ pihole.password }}"
          volumes:
            - '{{ pihole_config_dir }}/etc-pihole:/etc/pihole'
            - '{{ pihole_config_dir }}/etc-dnsmasq.d:/etc/dnsmasq.d'
          restart: always
          