- ansible.builtin.file:
    path: "{{ docker_registry_storage_dir }}"
    state: directory
    mode: '0755'


- community.docker.docker_compose:
    project_name: registry
    
    definition:
      version: '3.1'
      services:
        registry:
          restart: always
          image: registry:2
          container_name: registry
          ports:
            - 5000:5000
          volumes:
            - '{{ docker_registry_storage_dir }}:/var/lib/registry'