- name: Ensure traekfik config directory exists
  ansible.builtin.file:
    path: "{{ traefik_config_dir }}"
    state: directory

- name: Ensure traekfik config/certs directory exists
  ansible.builtin.file:
    path: "{{ traefik_config_dir }}/certs"
    state: directory

- name: Ensure traekfik dynamic config directory exists
  ansible.builtin.file:
    path: "{{ traefik_dynamic_config_dir }}"
    state: directory

- name: Create acme.json empty file
  ansible.builtin.file:
    path: "{{ traefik_config_dir }}/acme.json"
    state: touch
    mode: '600'
    modification_time: preserve
    access_time: preserve

- name: Create access.log empty file
  ansible.builtin.file:
    path: "{{ traefik_config_dir }}/access.log"
    state: touch
    modification_time: preserve
    access_time: preserve

- name: Copy static config file to remote
  ansible.builtin.copy:
    src: traefik.yml
    dest: "{{ traefik_config_dir }}/traefik.yml"
  notify:
    - Restart traefik container

- name: Copy dynamic config file to remote
  ansible.builtin.copy:
    src: conf.yml
    dest: "{{ traefik_dynamic_config_dir }}/conf.yml"
  notify:
    - Restart traefik container

- name: Ensure traefik is running
  community.docker.docker_compose:
    project_name: traefik

    definition:
      version: '3.2'
      services:
        tcd:
          image: ldez/traefik-certs-dumper:v2.8.1
          entrypoint: sh -c '
            apk add jq
            ; while ! [ -e /data/acme.json ]
            || ! [ `jq ".[] | .Certificates | length" /data/acme.json` != 0 ]; do
            sleep 1
            ; done
            && traefik-certs-dumper file --version v2 --watch
            --source /data/acme.json --dest /data/certs'
          volumes:
            - /{{ traefik_config_dir }}/acme.json:/data/acme.json
            - /{{ traefik_config_dir }}/certs:/data/certs

        traefik:
          restart: always
          container_name: traefik
          image: traefik:v2.10
          environment:
            CLOUDFLARE_DNS_API_TOKEN: "{{ traefik_cloudflare_token }}"
          ports:
            - "8022:8022"
            - "8080:8080"
            - "80:80"
            - "443:443"
            - "19943:19943"
          volumes:
            - /{{ traefik_config_dir }}/traefik.yml:/etc/traefik/traefik.yml
            - /{{ traefik_config_dir }}/acme.json:/etc/traefik/acme.json
            - /{{ traefik_config_dir }}/access.log:/etc/traefik/access.log
            - /{{ traefik_dynamic_config_dir }}:/etc/traefik/conf.d/
