- name: Create grafana data directory
  ansible.builtin.file:
    path: "{{ grafana_data_dir }}"
    state: directory
    mode: '0755'  

- name: Create loki config directory
  ansible.builtin.file:
    path: "{{ loki_config_dir }}"
    state: directory
    mode: '0755'  

- name: Copy loki config file to remote
  register: loki_config
  ansible.builtin.copy:
    src: ./files/loki-config.yml
    dest: "{{ loki_config_dir }}/loki-config.yml"

- name: Create promtail config directory
  ansible.builtin.file:
    path: "{{ promtail_config_dir }}"
    state: directory
    mode: '0755'  

- name: Copy promtail config file to remote
  register: promtail_config
  ansible.builtin.copy:
    src: ./files/promtail-config.yml
    dest: "{{ promtail_config_dir }}/promtail-config.yml"

- community.docker.docker_compose:
    project_name: grafana_loki
    
    definition:
      version: "3.1"
      networks:
        loki:
      services:
        loki:
          image: grafana/loki:2.4.0
          container_name: loki
          restart: always
          command: -config.file=/etc/loki/loki-config.yml
          ports:
            - "3100:3100"
          volumes:
            - "{{ loki_config_dir }}:/etc/loki"
          networks:
            - loki
        promtail:
          image: grafana/promtail:2.4.0
          container_name: promtail
          restart: always
          command: -config.file=/etc/promtail/promtail-config.yml
          volumes:
            - "{{ promtail_config_dir }}:/etc/promtail"
          networks:
            - loki
        grafana:
          image: grafana/grafana-enterprise:latest
          container_name: grafana
          restart: always
          environment:
            GF_AUTH_ANONYMOUS_ENABLED: 'true'
            GF_AUTH_ANONYMOUS_ORG_NAME: 'Main Org.'
            GF_AUTH_ANONYMOUS_ORG_ROLE: 'Admin'
            GF_AUTH_BASIC_ENABLED: 'false'
            GF_AUTH_DISABLE_LOGIN_FORM: 'true'
          ports:
            - "3000:3000"
          user: "{{ host_puid }}"
          networks:
            - loki
          volumes:
            - "{{ grafana_data_dir }}:/var/lib/grafana"


- name: Restart loki container
  docker_container:
    name: loki
    restart: true
  when: loki_config.changed

- name: Restart promtail container
  docker_container:
    name: promtail
    restart: true
  when: promtail_config.changed