
- name: Setup drone runner
  community.docker.docker_compose:
    project_name: drone_runner
    definition:
      version: '3'
      services:
        drone_server:
          container_name: drone_runner
          image: drone/drone-runner-docker:1
          environment:
            DRONE_RPC_PROTO: https
            DRONE_RPC_HOST: "{{ drone_server_host }}"
            DRONE_RPC_SECRET: "{{ drone_shared_secret }}"
            DRONE_RUNNER_CAPACITY: 2
            DRONE_RUNNER_NAME: "{{ drone_runner_name }}"
          restart: always
          ports:
            - 3000:3000
          volumes:
            - /var/run/docker.sock:/var/run/docker.sock
