---
all:
  children:
    kubernetes_controllers:
      hosts:
        tf-prod-k8s-controller-1:

    kubernetes_workers:
      hosts:
        tf-prod-k8s-worker-1:
        tf-prod-k8s-worker-2:
        tf-prod-k8s-worker-3:

  hosts:
    tf-prod-k8s-controller-1:
      ansible_host: 192.168.6.24
      ansible_user: firebolt
      ansible_password: "{{ inventoryPasswords.kubernetes_node }}"
      ansible_sudo_pass: "{{ inventoryPasswords.kubernetes_node }}"
      host_type: virtual

    tf-prod-k8s-worker-1:
      ansible_host: 192.168.6.25
      ansible_user: firebolt
      ansible_password: "{{ inventoryPasswords.kubernetes_node }}"
      ansible_sudo_pass: "{{ inventoryPasswords.kubernetes_node }}"
      host_type: virtual

    tf-prod-k8s-worker-2:
      ansible_host: 192.168.6.26
      ansible_user: firebolt
      ansible_password: "{{ inventoryPasswords.kubernetes_node }}"
      ansible_sudo_pass: "{{ inventoryPasswords.kubernetes_node }}"
      host_type: virtual

    tf-prod-k8s-worker-3:
      ansible_host: 192.168.6.27
      ansible_user: firebolt
      ansible_password: "{{ inventoryPasswords.kubernetes_node }}"
      ansible_sudo_pass: "{{ inventoryPasswords.kubernetes_node }}"
      host_type: virtual
