- name: Install qemu guest agent
  hosts: kubernetes_servers
  become: true
  tasks:
      - name: apt
        apt:
          update_cache: true
          upgrade: true
      - name: install qemu-guest-agent
        apt:
          name: qemu-guest-agent
          state: present
          update_cache: true
