
- name: Install NFS common utils
  hosts:
    - kubernetes_servers
  become: true
  tasks:
    - name: Install kubernetes tools
      ansible.builtin.apt:
        name:
          - nfs-common
        state: present
        update_cache: yes

