- name: Install containerd.io
  hosts:
    - kubernetes_servers
  become: true
  tasks:
    - name: Apt - Install prerequsites
      apt:
        update_cache: yes
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present

    - name: Add docker apt repository key.
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/debian/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: '0644'
        force: true

    - name: Get DEB architecture
      ansible.builtin.command: dpkg --print-architecture
      register: deb_architecture

    - name: Add Docker APT repository (debug)
      debug:
        msg: deb [arch={{ deb_architecture.stdout }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/{{ ansible_system | lower }}/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable


    - name: Add Docker APT repository
      apt_repository:
        repo: deb [arch={{ deb_architecture.stdout }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/{{ ansible_system | lower }}/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable

    - name: Install containerd.io
      apt:
        name: containerd.io
        update_cache: yes

    - name: Make sure containerd service is running
      ansible.builtin.systemd_service:
        state: started
        name: containerd

- name: Setup permissions
  hosts:
    - kubernetes_servers
  become: true
  roles:
    - role: abbottland.docker.docker_permissions
  tasks:
    - name: Change group ownership of /etc/containerd.sock
      ansible.builtin.file:
        path: /run/containerd/containerd.sock
        group: docker

- name: Configure containerd
  hosts:
    - kubernetes_servers
  become: true
  handlers:
    - name: Restart containerd
      ansible.builtin.systemd_service:
        name: containerd
        state: restarted
  tasks:
    - name: Copy config.toml to remote
      ansible.builtin.copy:
        src: ./files/config.toml
        dest: /etc/containerd/config.toml
      notify: Restart containerd
