
- name: Install Kubernetes Tools
  hosts:
    - kubernetes_servers
  become: true
  vars:
    apt_install_packages:
      - apt-transport-https
      - ca-certificates
      - curl
  roles:
    - role: abbottland.core.apt
  tasks:
    - name: Add kubernetes apt repository key.
      ansible.builtin.get_url:
        url: https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key
        dest: /etc/apt/keyrings/kubernetes-apt-keyring.asc
        mode: '0644'
        force: true

    - name: Add the Kubernetes apt repository
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.asc] https://pkgs.k8s.io/core:/stable:/v1.30/deb/ /"
        state: present
        filename: kubernetes
        update_cache: yes

    - name: Install kubernetes tools
      ansible.builtin.apt:
        name:
          - kubectl
          - kubeadm
          - kubelet
        state: present
        update_cache: yes

    - name: Hold packages
      loop:
        - kubectl
        - kubeadm
        - kubelet
      ansible.builtin.dpkg_selections:
        name: "{{ item }}"
        selection: hold

    - name: Enable and start the kubelet service
      ansible.builtin.systemd_service:
        name: kubelet
        state: started
        enabled: true

- name: Install Helm
  hosts: kubernetes_controller
  become: true
  vars:
    apt_install_packages:
      - apt-transport-https
  roles:
    - role: abbottland.core.apt
  tasks:
    - name: Add helm apt repository key.
      ansible.builtin.get_url:
        url: https://baltocdn.com/helm/signing.asc
        dest: /etc/apt/keyrings/helm.asc
        mode: '0644'
        force: true

    - name: Add the helm apt repository
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/etc/apt/keyrings/helm.asc] https://baltocdn.com/helm/stable/debian/ all main"
        state: present
        filename: helm
        update_cache: yes

    - name: Install helm
      ansible.builtin.apt:
        name:
          - helm
        state: present
        update_cache: yes
