- name: Label Kubernetes node as physical
  hosts:
    - kubernetes_controller
  tasks:
    - name: Label node as physical
      ansible.builtin.command: kubectl label node dumbledore host_type=physical --overwrite
      register: label_node_result
      ignore_errors: yes

- name: Update IP Tables to use legacy mode
  hosts:
    - kubernetes_servers
    - kubernetes_external_workers
  become: true
  tasks:
    - name: Ensure iptables uses legacy backend
      command: update-alternatives --set iptables /usr/sbin/iptables-legacy

    - name: Verify iptables version
      command: iptables --version
      register: iptables_version
      changed_when: false

    - name: Show iptables version
      debug:
        msg: "{{ iptables_version.stdout }}"


- name: Disable IPv6 on Kubernetes nodes
  hosts:
    - kubernetes_servers
    - kubernetes_external_workers
  become: true
  vars:
    reboot_after_disable: true
  tasks:
    - name: Create sysctl config to disable IPv6
      copy:
        dest: /etc/sysctl.d/99-disable-ipv6.conf
        content: |
          net.ipv6.conf.all.disable_ipv6 = 1
          net.ipv6.conf.default.disable_ipv6 = 1
        owner: root
        group: root
        mode: '0644'

    - name: Reload sysctl settings
      command: sysctl --system

    - name: Reboot the node (if enabled)
      reboot:
        msg: "Rebooting to apply IPv6 disablement"
        pre_reboot_delay: 3
        reboot_timeout: 300
      when: reboot_after_disable
