
- name: Create vector config directory
  ansible.builtin.file:
    path: "{{ vector_config_directory }}"
    state: directory
    mode: '0755'  

# TODO: make this idempotent
- name: Copy vector.toml to remote
  ansible.builtin.copy:
    src: ./files/vector.toml
    dest: "/tmp/vector.toml"

- name: Replace vector host
  replace:
    path: /tmp/vector.toml
    regexp: 'VECTOR_LOKI_HOST'
    replace: "{{ vector_loki_host }}"

- name: Replace existing vector.toml
  ansible.builtin.copy:
    remote_src: true
    src: /tmp/vector.toml
    dest: "{{ vector_config_directory }}/vector.toml"
  notify:
    - Restart vector container

- name: Deploy vector container via docker-compose
  community.docker.docker_compose:
    project_name: vector
    recreate: "always"
    definition:
      version: "3.1"
      networks: "{{ vector_compose_networks }}"
      services:
        vector:
          image: timberio/vector:0.18.1-debian
          container_name: vector
          restart: always
          ports:
            - "8383:8383"
          volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - "{{ vector_config_directory }}/vector.toml:/etc/vector/vector.toml:ro"
          networks: "{{ vector_compose_service_network }}"
            
          # TODO: Consider adding a command for multiple files
          # https://vector.dev/docs/reference/configuration/#multiple-files