
- name: Create vector config directory
  ansible.builtin.file:
    path: "{{ vector_config_directory }}"
    state: directory
    mode: '0755'  

- name: Copy vector.toml to remote
  ansible.builtin.copy:
    src: ./files/vector.toml
    dest: "/tmp/vector.toml"

- name: Replace vector host
  replace:
    path: /tmp/vector.toml
    regexp: 'VECTOR_LOKI_HOST'
    replace: "{{vector_loki_host}}"

- name: Replace existing vector.toml
  ansible.builtin.copy:
    remote_src: true
    src: /tmp/vector.toml
    dest: "{{ vector_config_directory }}/vector.toml"
  register: vector_conf

- community.docker.docker_compose:
    project_name: vector
    definition:
      version: "3.1"
      services:
        vector:
          image: timberio/vector:0.18.1-debian
          container_name: vector
          restart: always
          ports:
            - "8383:8383"
          volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - "{{ vector_config_directory }}/vector.toml:/etc/vector/vector.toml:ro"

- name: Restart vector container
  docker_container:
    name: vector
    restart: true
  when: vector_conf.changed