global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'codelab-monitor'


scrape_configs:
  # Gaming PC


  - job_name: 'home_file_service'
    static_configs:
      - targets: ['192.168.4.90:4000']

  - job_name: 'windows_exporter'
    static_configs:
      - targets: ['192.168.4.134:9182']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['192.168.4.24:9100']
        labels:
          instance: raspberrypi
      - targets: ['192.168.4.144:9100']
        labels:
          instance: bananapi
      - targets: ['192.168.4.157:9100']
        labels:
          instance: dumbledore
      # Note: 172.17.0.1 is how we access the host from within docker (works on linux, whereas host.docker.internal works with docker-desktop)
      - targets: ['192.168.4.124:9100']
        labels:
          instance: room_of_requirement

  - job_name: 'docker'
    static_configs:
      - targets: ['192.168.4.24:9323']
        labels:
          instance: raspberrypi
      - targets: ['192.168.4.144:9323']
        labels:
          instance: bananapi
      - targets: ['192.168.4.157:9323']
        labels:
          instance: dumbledore
      - targets: ['192.168.4.124:9323']
        labels:
          instance: room_of_requirement

  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
        labels:
          instance: room_of_requirement

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          instance: room_of_requirement

  - job_name: 'traefik'
    static_configs:
      - targets: ['192.168.4.144:8080']
        labels:
          instance: bananapi
