FROM python:3

# Install packages with apt
RUN apt-get update \
	&& apt-get install -y \
	curl \
	git \
	golang \
	sudo \
	vim \
	wget \
	jq \
	sshpass \
	zsh \
	neofetch \
	&& rm -rf /var/lib/apt/lists/*

# Setup user and home dir
ARG USER=coder
RUN useradd --groups sudo --no-create-home --shell /usr/bin/zsh ${USER} \
	&& echo "${USER} ALL=(ALL) NOPASSWD:ALL" >/etc/sudoers.d/${USER} \
	&& chmod 0440 /etc/sudoers.d/${USER}

RUN mkdir -p /home/${USER} \
	&& chown -R ${USER} /home/${USER}

USER ${USER}
WORKDIR /home/${USER}
COPY .zshrc /home/${USER}/.zshrc

ENV PATH="${PATH}:/home/${USER}/.local/bin"

# Install pip packages
RUN pip3 install \
    ansible \
    paramiko \
    pyopenssl \
    pywinrm \
    pre-commit
