# Note: docker needs to be installed manually onto room_of_requirement!
- name: Install Docker
  hosts:
    - bananapi
    - rpi
  become: true
  roles:
    - role: abbottland.docker.docker
    - role: abbottland.docker.docker_permissions
