# Note: docker needs to be installed manually onto room_of_requirement!
- name: Install Docker
  hosts:
    - bananapi
    - rpi
  become: true
  roles:
    - role: abbottland.docker.docker
    - role: abbottland.docker.docker_permissions
    - role: abbottland.docker.docker_daemon
      docker_daemon_key: 'experimental'
      docker_daemon_value: true
    - role: abbottland.docker.docker_daemon
      docker_daemon_key: 'live-restore'
      docker_daemon_value: true