
- name: Docker Installations on Banana PI (not root)
  hosts: bananapi
  roles:
    - role: abbottland.dns.pihole
    - role: abbottland.dns.cloudflare_ddns

# TODO: consider adding resolver to room_of_requirement
- name: DNS Resolvers
  hosts:
    - web_servers
  become: true
  roles:
    - role: abbottland.dns.dns_resolver
