
- name: Setup DNS network on bananapi
  hosts: bananapi
  tasks:
    - name: Create a network with custom IPAM config
      community.docker.docker_network:
        name: custom-dns
        driver: bridge
        ipam_driver: default

        ipam_config:
          - subnet: 172.31.0.0/24

- name: Docker Installations on Banana PI (not root)
  hosts: bananapi
  roles:
    - role: abbottland.dns.pihole
    - role: abbottland.dns.cloudflare_ddns

# TODO: consider adding resolver to room_of_requirement
- name: DNS Resolvers
  hosts:
    - web_servers
  become: true
  roles:
    - role: abbottland.dns.dns_resolver
