- name: DDNS and Traefik Installation on Banana PI via Docker (not root)
  hosts: bananapi
  roles:
    - role: abbottland.ingress.traefik
      traefik_cloudflare_token: "{{ cloudflare.token }}"

    - role: abbottland.ingress.traefik_app
      traefik_app_file_name: 'pihole.local.yml'