


- name: Copy Local SSH Public Key to remote computer
  include_role:
    name: ryankwilliams.ssh_copy_id
  vars:
    hostname: "{{ target.ansible_host }}"
    username: "{{ target.ansible_user }}"
    password: "{{ target.ansible_password }}"
    ssh_public_key: "{{ lookup('env','HOME') }}/.ssh/id_rsa.pub"
    ssh_port: 22
