- name: Update Apt
  ansible.builtin.apt:
    upgrade: true
    update_cache: true

- name: Ensure apt packages are installed
  ansible.builtin.apt:
    name: "{{ item.name | default(item) }}"
    update_cache: true
  loop: "{{ apt_install_packages }}"
