http:
  routers:
    to-proxmox-https:
      entryPoints:
        - "https"
      rule: "Host(`proxmox.local.abbottland.io`)"
      middlewares:
        - secured
      tls: {}
      service: proxmox

  services:
    proxmox:
      loadBalancer:
        servers:
          - url: https://192.168.4.170:8006
        passHostHeader: true
