argument_specs:
  main:
    options:
      drone_server_host:
        type: 'str'
        description: "Hostname of drone server (URI)"
        required: true
      drone_data_dir:
        type: 'str'
        description: "Directory for drone data"
        required: true
      drone_github_client_id:
        type: 'str'
        description: "Github Client ID for app"
        required: true
      drone_github_client_secret:
        type: 'str'
        description: "Github Client Secret for app"
        required: true
      drone_shared_secret:
        type: 'str'
        description: "Shared secret between drone website and runners"
        required: true
      drone_server_user_filter:
        type: 'str'
        description: "Comma-separated list of github usernames that are allowed to access this server"
        required: true
      drone_server_admin:
        type: 'str'
        description: "Github username to set as admin of server"
        required: true