- ansible.builtin.file:
    path: "{{ traefik_config_dir }}"
    state: directory

- name: Copy config file to remote
  register: conf
  ansible.builtin.copy:
    src: traefik.yml
    dest: "{{ traefik_config_dir }}/traefik.yml"

- community.docker.docker_compose:
    project_name: traefik
    
    definition:
      version: '3.2'
      services:
        portainer:
          restart: always
          container_name: traefik
          image: traefik:v2.9
          ports:
            - "8080:8080"
            - "80:80"
          volumes:
            - /{{ traefik_config_dir }}/traefik.yml:/etc/traefik/traefik.yml

