- name: Create grafana data directory
  ansible.builtin.file:
    path: "{{ grafana_data_dir }}"
    state: directory
    mode: '0755'

- name: Create loki config directory
  ansible.builtin.file:
    path: "{{ loki_config_dir }}"
    state: directory
    mode: '0755'

- name: Create loki data directory
  ansible.builtin.file:
    path: "{{ loki_data_dir }}"
    state: directory
    mode: '0755'

- name: Copy loki config file to remote
  notify:
    - Restart loki container
  ansible.builtin.copy:
    src: ./files/loki-config.yml
    dest: "{{ loki_config_dir }}/loki-config.yml"

- name: Ensure grafana & loki are up-and-running
  community.docker.docker_compose:
    project_name: grafana_loki
    # recreate: "always"
    definition:
      version: "3.1"
      networks:
        loki:
          name: grafana_loki
          driver: bridge
      services:
        loki:
          image: grafana/loki:2.4.0
          container_name: loki
          restart: always
          command: -config.file=/etc/loki/loki-config.yml
          user: "{{ host_puid }}"
          ports:
            - "3100:3100"
          volumes:
            - "{{ loki_data_dir }}:/loki_data"
            - "{{ l
            oki_config_dir }}:/etc/loki"
          networks:
            - loki
        grafana:
          image: grafana/grafana-enterprise:latest
          container_name: grafana
          restart: always
          environment:
            GF_AUTH_ANONYMOUS_ENABLED: 'true'
            GF_AUTH_ANONYMOUS_ORG_NAME: 'Main Org.'
            GF_AUTH_ANONYMOUS_ORG_ROLE: 'Admin'
            GF_AUTH_BASIC_ENABLED: 'false'
            GF_AUTH_DISABLE_LOGIN_FORM: 'true'
          ports:
            - "3000:3000"
          user: "{{ host_puid }}"
          networks:
            - loki
          volumes:
            - "{{ grafana_data_dir }}:/var/lib/grafana"
