# TODO: Update this script to support both debian and ubuntu
# TODO: Update this script to support multiple architectures

- name: Apt - Install prerequsites
  apt:
    update_cache: yes
    name: 
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present

- name: Add Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg

# TODO: make this idempotent
- name: Get DEB architecture
  ansible.builtin.command: dpkg --print-architecture
  register: deb_architecture

- name: Add Docker APT repository
  apt_repository:
    repo: deb [arch={{ deb_architecture.stdout }}] https://download.docker.com/{{ ansible_system | lower }}/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable

- name: Install Docker CE
  apt:
    name: 
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
    update_cache: yes
