
- name: Add GH GPG key
  apt_key:
    url: https://cli.github.com/packages/githubcli-archive-keyring.gpg


# TODO: update to work on PI, not just localhost
- name: Add GH APT repository
  apt_repository:
    repo: deb [arch=amd64] https://cli.github.com/packages stable main

- name: Install GH CLI
  apt:
    name:
      - gh
    update_cache: yes
