host_puid: "1000"
host_pgid: "1000"

dns_nameservers: 
  - "127.0.0.1"

pip_install_packages:
  - docker
  - docker-compose

traefik_config_dir: /home/pi/app_config/traefik
traefik_dynamic_config_dir: /home/pi/app_config/traefik/conf.d

pihole_config_dir: /home/pi/app_config/pihole

docker_daemon_registry_mirror: https://registry-mirror.nas.local.abbottland.io