ansible_password: "{{ inventoryPasswords.bananapi }}"
ansible_sudo_pass: "{{ inventoryPasswords.bananapi }}"

cron_scripts_dir: /home/pi/scripts

# bananapi is dns server and should loop back to self
dns_nameservers:
  - "127.0.0.1"

traefik_config_dir: /home/pi/app_config/traefik
traefik_dynamic_config_dir: /home/pi/app_config/traefik/conf.d
traefik_docker_image: traefik:v2.11.2

tcd_docker_image: ldez/traefik-certs-dumper:v2.8.3

pihole_docker_image: pihole/pihole:2024.05.0
pihole_config_dir: /home/pi/app_config/pihole

wireguard_config_dir: /home/pi/app_config/wireguard/config
