pip_install_packages:
  - paramiko
  - pywinrm

shell_config_aliases:
  - alias: ll
    command: ls -lh
  - alias: python
    command: python3
  - alias: sp
    command: "source ~/.zprofile"
# NOTE: Name does not match 'shell_config_exports' on purpose
shell_config_custom_exports: 
  - key: PATH
    value: "$PATH:$HOME/.local/bin"
  - key: GITHUB_TOKEN
    value: "{{ drone.github_pat }}"
  - key: NODE_ENV
    value: "development"
shell_config_ssh_targets:
  - shortcut: bpi
    username: "{{ hostvars.bananapi.ansible_user }}"
    hostname: "{{ hostvars.bananapi.ansible_host }}"
  - shortcut: rpi
    username: "{{ hostvars.rpi.ansible_user }}"
    hostname: "{{ hostvars.rpi.ansible_host }}"
  - shortcut: ror
    username: "{{ hostvars.room_of_requirement.ansible_user }}"
    hostname: "{{ hostvars.room_of_requirement.ansible_host }}"
  - shortcut: elderwand
    username: "{{ hostvars.elder_wand.ansible_user }}"
    hostname: "{{ hostvars.elder_wand.ansible_host }}"

docker_daemon_registry_mirror: https://registry-mirror.nas.local.abbottland.io