- ansible.builtin.file:
    path: /home/pi/drone_data
    state: directory
    mode: '0755'  

- community.docker.docker_compose:
    project_name: drone_server
    
    definition:
      version: '3'
      networks:
        default:
          name: lsio
          external: true
      services:
        drone_server:
          container_name: drone
          image: drone/drone:2
          environment:
            DRONE_GITHUB_CLIENT_ID: "{{ drone.github_client_id }}"
            DRONE_GITHUB_CLIENT_SECRET: "{{ drone.github_client_secret }}"
            DRONE_RPC_SECRET: "{{ drone.shared_secret }}"
            DRONE_SERVER_HOST: drone.abbottland.duckdns.org
            DRONE_SERVER_PROTO: http
            DRONE_USER_FILTER: pbabbott
          volumes:
            - /home/pi/drone_data:/data
          restart: unless-stopped
          ports:
            - 9926:80