- name: Ensure drone data directory exists
  ansible.builtin.file:
    path: "{{ drone_data_dir }}"
    state: directory
    mode: '0755'

- name: Setup drone server
  community.docker.docker_compose:
    project_name: drone_server

    definition:
      version: '3'
      services:
        drone_server:
          container_name: drone
          image: drone/drone:2
          environment:
            DRONE_GITHUB_CLIENT_ID: "{{ drone_github_client_id }}"
            DRONE_GITHUB_CLIENT_SECRET: "{{ drone_github_client_secret }}"
            DRONE_RPC_SECRET: "{{ drone_shared_secret }}"
            DRONE_SERVER_HOST: "{{ drone_server_host }}"
            DRONE_SERVER_PROTO: https
            DRONE_USER_FILTER: "{{ drone_server_user_filter }}"
            DRONE_USER_CREATE: "username:{{ drone_server_admin }},admin:true"
          volumes:
            - "{{ drone_data_dir }}:/data"
          restart: unless-stopped
          ports:
            - 9926:80
