

- ansible.builtin.file:
    path: /home/pi/duckdns
    state: directory
    mode: '0755'  

- community.docker.docker_compose:
    project_name: duckdns
    
    definition: 
      version: "2.1"
      networks:
        default:
          name: lsio
          external: true
      services:
        duckdns:
          container_name: duckdns
          image: lscr.io/linuxserver/duckdns:latest
          restart: always
          environment:
            PUID: "{{ host_puid }}"
            PGID: "{{ host_pgid }}"
            TZ: "{{ host_tz }}"
            SUBDOMAINS: abbottland
            TOKEN: "{{ duckdns.token }}"
            LOG_FILE: 'false'
          volumes:
            - /home/pi/duckdns/config:/config #optional
          