

argument_specs:
  main:
    options:
      docker_daemon_skip_restart:
        type: "bool"
      docker_daemon_key:
        required: true
        type: "str"
        description: "key for dameon settings"
      docker_daemon_value:
        required: true
        type: "raw"
        description: "raw value for dameon settings"
      docker_daemon_directory:
        required: false
        type: str
        description: "Directory where docker daemon.json lives."