# ---
# - name: Install apt packages
#   hosts:
#     - rpi
#     - bananapi
#   become: true
#   roles:
#     - abbottland.core.apt

# - name: Install pip packages
#   hosts:
#     - rpi
#     - bananapi
#     - room_of_requirement
#   roles:
#     - role: abbottland.core.pip
#       become: true

# TODO: This is for home-file-service only
- name: Install node-windows globally on elder_wand
  hosts: elder_wand
  tasks:
    - name: Install node-windows
      #ansible.builtin.win_shell
      ansible.windows.win_shell: npm install -g node-windows
      args:
        creates: C:\Users\pbabb\AppData\Roaming\npm\node_modules\node-windows
