
- name: Docker Installations on Banana PI (not root)
  hosts: bananapi
  roles:
     - role: abbottland.dns.pihole

- name: DNS Resolvers
  hosts:
    - bananapi
    - rpi
  become: true
  roles:
    - role: abbottland.dns.dns-resolver
