
# TODO: Consider having each server have its own traefik instance
# for now, bananapi will manage all traffic across all servers

- name: DDNS and Traefik Installation on Banana PI via Docker (not root)
  hosts: bananapi
  roles:
    - role: home.traefik
  vars:
    traefik_files:
      # Banana PI
      # - pihole.local.yml
      # Raspberry PI
      - drone.yml
      - mealie.yml
      - dashboard.local.yml
      # Room Of Requirement
      - plex.yml
      - portal.nas.local.yml
      - portainer.nas.local.yml
      # - registry.nas.local.yml
      - handbrake.nas.local.yml
      # - verdaccio.nas.local.yml
      - grafana.nas.local.yml
      - loki.nas.local.yml

  tasks:
    - name: "Copy traefik config {{ item }} to remote"
      ansible.builtin.copy:
        src: "./traefik/{{ item }}"
        dest: "{{ traefik_dynamic_config_dir }}/{{ item }}"
      loop: "{{ traefik_files }}"
      