
- name: DDNS and Traefik Installation on Banana PI via Docker (not root)
  hosts: bananapi
  roles:
    - role: home.cloudflare-ddns
    - role: home.traefik
  vars:
    traefik_files:
      # Public Access
      - drone.yml
      - mealie.yml
      - plex.yml
      # LAN Only`
      - dashboard.local.yml
      - pihole.local.yml
      - portal.nas.local.yml
      - portainer.nas.local.yml
      - registry.nas.local.yml
  tasks:
    - name: Enable mealie in proxy
      ansible.builtin.copy:
        src: "./traefik/{{ item }}"
        dest: "{{ traefik_dynamic_config_dir }}/{{ item }}"
      loop: "{{ traefik_files }}"
      