
# TODO: Consider having each server have its own traefik instance
# for now, bananapi will manage all traffic across all servers

- name: DDNS and Traefik Installation on Banana PI via Docker (not root)
  hosts: bananapi
  roles:
    - role: home.traefik
  vars:
    traefik_files:
      - grafana.nas.local.yml
      - loki.nas.local.yml

  tasks:
    - name: "Copy traefik config {{ item }} to remote"
      ansible.builtin.copy:
        src: "./traefik/{{ item }}"
        dest: "{{ traefik_dynamic_config_dir }}/{{ item }}"
      loop: "{{ traefik_files }}"
      