
- name: Setup Docker Registry on NAS
  hosts: room_of_requirement
  roles:
    - role: home.docker-registry

# # TODO: https://joxit.dev/docker-registry-ui/

- name: Setup Docker Registry
  become: true
  hosts: 
    - bananapi
    - rpi
  roles:
    - role: home.docker_daemon
      ip_address: "{{ ansible_host }}"
      # docker_registry_mirror_host: "{{docker_registry_mirror_host}}"
    