
- name: Setup Docker Registry on NAS
  hosts: room_of_requirement
  roles:
    - role: home.docker-registry

- name: Setup Docker Registry as pull through cache
  become: true
  hosts: 
    - bananapi
    - rpi
  roles:
    - role: home.docker_daemon
      ip_address: "{{ ansible_host }}"
    
- name: Setup NPM Registry on NAS 
  hosts: room_of_requirement
  roles:
    - role: home.verdaccio

