- name: Drone Docker Installations on RPI (not root)
  hosts: rpi
  roles:
    - role: home.drone-server
    - role: home.drone-docker-runner

# TODO: Setup elder_wand drone configuration with ansible.