# - name: Configure NAS 
#   hosts: room_of_requirement
#   roles:
#     - role: home.handbrake

- name: Docker Installations on RPI (not root)
  hosts: rpi
  roles:
    # - role: home.dashy
    - role: home.mealie
#     - role: home.portainer

#     - role: home.prometheus-server
    
#     - role: home.grafana
#     - role: home.home-assistant
    