- name: Configure elder_wand
  hosts: elder_wand
  tasks:
    - name: Firewall rule to allow HTTP on TCP port 9182
      community.windows.win_firewall_rule:
        name: Prometheus Metrics
        localport: 9182
        action: allow
        direction: in
        protocol: tcp
        profiles: private
        state: present
        enabled: yes

- name: Configure NAS 
  hosts: room_of_requirement
  roles:
    - role: home.prometheus-docker-node-exporter

- name: Install log driver plugin
  hosts:
    - room_of_requirement
  roles:
    - role: home.docker-plugins

- name: Docker Installations (not root)
  hosts: 
    - room_of_requirement
  roles:
    - role: home.grafana-loki
    # - role: home.prometheus-server

- name: RPI to send logs to loki
  hosts: 
    - rpi
  roles:
    - role: home.vector


- name: Setup room_of_requirement docker daemon to send logs to loki
  become: true
  hosts: 
    - room_of_requirement
  environment:
    PATH: "{{ ansible_env.PATH }}:/usr/builtin/sbin"
  roles:
    - role: home.docker_daemon
      docker_daemon_metrics_ip_address: "{{ ansible_host }}"
      docker_daemon_loki_log_sink: "localhost:3100"
      docker_daemon_skip_restart: true
  tasks:
    - name: Restart docker daemon the hard way
      when: docker_daemon_changed
      block:
        - name: stop docker
          ansible.builtin.command: /usr/local/AppCentral/docker-ce/CONTROL/start-stop.sh stop
        - name: start docker
          ansible.builtin.command: /usr/local/AppCentral/docker-ce/CONTROL/start-stop.sh start
  