
- name: Docker Installations on PI (not root)
  hosts: bananapi
  roles:
    - role: home.cloudflare-ddns
    - role: home.traefik
    - role: home.pihole

- name: Self-reference as DNS server (root)
  hosts: bananapi
  become: true
  tasks:
    - name: self-reference dns
      copy:
        dest: /etc/dhcpcd.conf
        owner: root
        group: root
        mode: 0664
        content: |
          static domain_name_servers=127.0.0.1