
- name: Install python, docker, azure cli, and pip packages on host (executes as root)
  hosts: bananapi
  pre_tasks:
    - become: true
      block:
      - name: Update Apt
        ansible.builtin.apt:
          upgrade: yes
          update_cache: yes
      - name: Install Python3 pip
        ansible.builtin.apt:
          name: 
            - python3-pip
          update_cache: yes
  roles:
    - role: home.pip
      become: true
    - role: home.docker
      become: true
    - role: home.docker_permissions
    - role: home.docker_metrics
      become: true
      ip_address: "{{ ansible_host }}"
    - role: cloudalchemy.node_exporter