
- name: Docker Installations on RPI (not root)
  hosts: rpi
  pre_tasks:
    - name: Create a network
      community.docker.docker_network:
        name: lsio
  roles:
    - role: home.dashy
    - role: home.drone-server
    - role: home.drone-docker-runner
#     - role: home.portainer
#     - role: home.mealie
#     - role: home.prometheus-server
    
#     - role: home.grafana
#     - role: home.home-assistant
    

# - name: Backup important data to Azure each week
#   hosts: rpi
#   tasks:
#     - name: Zip backups
#       with_items: "{{ backup_jobs }}"
#       include_role:
#         name: home.zip.backup
#       vars:
#         path: "{{item.path}}"
#         dest: "{{item.dest}}"
#         job_name: "{{item.job_name}}"


