
# Loads default set of integrations. Do not remove.
default_config:

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1
    - 192.168.4.144
    - 192.168.4.0/24 # Local LAN Subnet
    - 172.17.0.0/24 # Docker Subnet
  ip_ban_enabled: true
  login_attempts_threshold: 5

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
