

- community.docker.docker_compose:
    project_name: node_exporter
    definition:
      version: '3.8'
      services:
        node_exporter:
          image: quay.io/prometheus/node-exporter:latest
          container_name: node_exporter
          command:
            - '--path.rootfs=/host'
          network_mode: host
          pid: host
          restart: always
          volumes:
            - '/:/host:ro'