http:
  middlewares:
    addprefix-pihole:
      addPrefix:
        prefix: "/admin"
    redirect-to-admin:
      redirectRegex:
        regex: "^https://pihole.local.abbottland.io/admin/$"
        replacement: "https://pihole.local.abbottland.io"
        permanent: true


  routers:
    to-pihole-admin-https:
      entryPoints:
        - "https"
      rule: "Host(`pihole.local.abbottland.io`)"
      middlewares:
        - secured
        - redirect-to-admin
        - addprefix-pihole
      tls: {}
      service: pihole

  services:
    pihole:
      loadBalancer:
        servers:
        - url: http://192.168.4.144:8081
        passHostHeader: true
