---
all:
  children:
    kubernetes_servers:
      hosts:
        tf-nonprod-k8s-controller-1:

    kubernetes_workers:
      hosts:
        tf-nonprod-k8s-worker-1:
        tf-nonprod-k8s-worker-2:
        tf-nonprod-k8s-worker-3:

  hosts:
    tf-nonprod-k8s-controller-1:
      ansible_host: 192.168.6.31
      ansible_user: firebolt
      ansible_password: "{{ inventoryPasswords.kubernetes_node }}"
      ansible_sudo_pass: "{{ inventoryPasswords.kubernetes_node }}"
      host_type: virtual

    tf-nonprod-k8s-worker-1:
      ansible_host: 192.168.6.32
      ansible_user: firebolt
      ansible_password: "{{ inventoryPasswords.kubernetes_node }}"
      ansible_sudo_pass: "{{ inventoryPasswords.kubernetes_node }}"
      host_type: virtual

    tf-nonprod-k8s-worker-2:
      ansible_host: 192.168.6.33
      ansible_user: firebolt
      ansible_password: "{{ inventoryPasswords.kubernetes_node }}"
      ansible_sudo_pass: "{{ inventoryPasswords.kubernetes_node }}"
      host_type: virtual

    tf-nonprod-k8s-worker-3:
      ansible_host: 192.168.6.34
      ansible_user: firebolt
      ansible_password: "{{ inventoryPasswords.kubernetes_node }}"
      ansible_sudo_pass: "{{ inventoryPasswords.kubernetes_node }}"
      host_type: virtual
