

- name: Ensure /etc/docker directory exists
  ansible.builtin.file:
    state: directory
    path: /etc/docker
    mode: '0755'  

- name: Write hostname using jinja2
  ansible.builtin.template:
    src: daemon.j2
    dest: /tmp/daemon.json

- name: Replace existing docker daemon.json
  ansible.builtin.copy:
    remote_src: true
    src: /tmp/daemon.json
    dest: /etc/docker/daemon.json
  register: docker_daemon

- name: Restart docker
  when: 
    - docker_daemon.changed
    - not docker_daemon_skip_restart
  ansible.builtin.systemd:
    state: restarted
    daemon_reload: yes
    name: docker

- name: Set docker daemon changed variable
  ansible.builtin.set_fact: "docker_daemon_changed={{ docker_daemon.changed }}"